### check updating phone with valid info 200
PATCH HTTP://localhost:5000/api/phones/1 HTTP/1.1
Content-Type: application/vnd.api+json

{
  "nfc": false
}

### check updating phone with invalid info 422
PATCH HTTP://localhost:5000/api/phones/2 HTTP/1.1
Content-Type: application/vnd.api+json

{
  "nfc": 25
}

### check updating not existing phone  404
PATCH HTTP://localhost:5000/api/phones/1110 HTTP/1.1
Content-Type: application/vnd.api+json

{
  "nfc": false
}